### ISSUE TITLE
How to update data in line chart ?

### ISSUE THREAD

**Issue by hoangtrongphuc** [jettro/c3-angular-directive#105]
I want update data in line chart from my API, but it's not woking, it's show empty chart.
HTML :
```
 <c3chart bindto-id="chart1">
                    <chart-column column-id="Req/s"
                                  column-values="{{data}}"
                                  column-type="spline"/> 
  </c3chart>
```
Angular :
```
.state('app.stats.index', {
          url: '',
          templateUrl: 'modules/stats/views/stat.html',
          controllerAs: 'ctrl',
          controller: function ($scope, StatsService, systems) {
            this.systems = systems;
            $scope.data = [];
            setInterval(function() {
              StatsService.getStats().then(function(result){
              $scope.data.push(result[0].server[0].ccu);
                console.log($scope.data);
              });
            }, 1000);
          },
          resolve: {
            systems: function (StatsService) {
              return StatsService.getStats();
            }
          }
        })
```

**Comment by jettro** [comment]
First thing I notice is the column-id that you use, not sure if strange characters like these work as an id. Would be good to have a working version somewhere in plunkr or something.

**Comment by RubenCordeiro** [comment]
You should use the `$interval` service instead of `setInterval`.

When `$interval` is used, Angular is aware of any scope changes made by the interval function, and the two-way binding reflects the changes.

When `setInterval` is used, Angular will not be aware of any scope changes made by the setInterval function.

I believe that this issue is not caused by this module. Can you confirm @hoangtrongphuc?
