### ISSUE TITLE
Customize Tooltip content

### ISSUE THREAD

**Issue by A-Allam** [jettro/c3-angular-directive#178]
I want to use the tooltip of a pie chart to show two things.  
The value and the percentage I attached an image with what I need
<img width="227" alt="screen shot 2018-02-18 at 2 11 24 pm" src="https://user-images.githubusercontent.com/2790655/36351751-2044bdc8-14b7-11e8-85c5-f5f7b2b5ece2.png">

**Comment by Slandais** [comment]
Hi,

you can do it with the contentFormatFunction directive.

Like this :

`<c3chart>
<chart-tooltip content-format-function="ctrl.tooltipContentFunction"/>
<c3chart>`


This directive is not documented here, but works like this others:
 http://jettro.github.io/c3-angular-directive/api-docs/1.3/chartTooltip.html
And you have the documentation of C3 here : http://c3js.org/reference.html#tooltip-contents

I found it with this fixed issue;
https://github.com/jettro/c3-angular-directive/issues/108
Available since the 1.3 version : https://github.com/jettro/c3-angular-directive#13
